# Generated by Django 4.0.6 on 2022-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CipherManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertieslist',
            name='scope',
            field=models.CharField(default='MAIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertieslist',
            name='type',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
    ]
