# Generated by Django 4.0.6 on 2022-12-05 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toolname', models.CharField(max_length=200)),
                ('filename', models.CharField(db_index=True, default='any.properties', max_length=100)),
                ('status', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 1, 43, 51, 674432))),
                ('threadId', models.CharField(default=-100, max_length=50)),
            ],
        ),
    ]
