# Generated by Django 4.0.6 on 2022-12-05 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolprofile',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 4, 19, 16, 444842)),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toolname', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('tool_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolprofile.toolprofile')),
            ],
        ),
    ]
